import 'package:get/get_navigation/src/routes/get_route.dart';
import 'package:grambix/bind/all_category_binding.dart';
import 'package:grambix/bind/forgot_password_binding.dart';
import 'package:grambix/bind/free_trial_binding.dart';
import 'package:grambix/bind/otp_verify_binding.dart';
import 'package:grambix/bind/pass_change_binding.dart';
import 'package:grambix/bind/reset_password_binding.dart';
import 'package:grambix/bind/top_books_binding.dart';
import 'package:grambix/bind/update_profile_binding.dart';
import 'package:grambix/views/all_category/screen/all_category_screen.dart';
import 'package:grambix/views/detail_preview/screen/detail_preview_screen.dart';
import 'package:grambix/views/free_trial/screen/free_trial_screen.dart';
import 'package:grambix/views/pass_change/screen/pass_change_screen.dart';
import 'package:grambix/views/top_books/screen/top_books_screen.dart';
import 'package:grambix/views/update_profile/screen/update_profile_screen.dart';
import '../bind/category_preview_binding.dart';
import '../bind/detail_preview_binding.dart';
import '../bind/faq_binding.dart';
import '../bind/find_binding.dart';
import '../bind/grambix_binding.dart';
import '../bind/home_binding.dart';
import '../bind/library_binding.dart';
import '../bind/login_binding.dart';
import '../bind/navigation_binding.dart';
import '../bind/offline_binding.dart';
import '../bind/offline_preview_binding.dart';
import '../bind/offline_read_binding.dart';
import '../bind/otp_binding.dart';
import '../bind/payment_binding.dart';
import '../bind/player_binding.dart';
import '../bind/policy_binding.dart';
import '../bind/preview_binding.dart';
import '../bind/profile_binding.dart';
import '../bind/reading_binding.dart';
import '../bind/register_binding.dart';
import '../bind/sp_binding.dart';
import '../bind/splash_bindings.dart';
import '../bind/subcription_binding.dart';
import '../bind/support_binding.dart';
import '../bind/terms_binding.dart';
import '../views/auth/forgot_password/screen/forgot_password_screen.dart';
import '../views/auth/login/screen/login_screen.dart';
import '../views/auth/otp_verify/screen/otp_verify_screen.dart';
import '../views/auth/register/screen/register_screen.dart';
import '../views/auth/reset_password/screen/reset_password_screen.dart';
import '../views/category_preview/screen/category_preview_screen.dart';
import '../views/faq/screen/faq_screen.dart';
import '../views/find/screen/find_screen.dart';
import '../views/navigations/grambix/screen/grambix_screen.dart';
import '../views/navigations/home/screen/home_screen.dart';
import '../views/navigations/library/screen/library_screen.dart';
import '../views/navigations/navigation/screen/navigation_screen.dart';
import '../views/navigations/profile/screen/profile_screen.dart';
import '../views/offline/offline_preview/screen/offline_preview_screen.dart';
import '../views/offline/offline_read/screen/offline_read_screen.dart';
import '../views/offline/screen/offline_screen.dart';
import '../views/otp/screen/otp_screen.dart';
import '../views/payment/screen/payment_screen.dart';
import '../views/player/screen/player_screen.dart';
import '../views/policy/screen/policy_screen.dart';
import '../views/preview/screen/preview_screen.dart';
import '../views/reading/screen/reading_screen.dart';
import '../views/sp/screen/sp_screen.dart';
import '../views/splash/screens/splash_screen.dart';
import '../views/subcription/screen/subcription_screen.dart';
import '../views/support/screen/support_screen.dart';
import '../views/terms/screen/terms_screen.dart';

part 'pages.dart';

class Routes {
  static var list = RoutePageList.list;
static const spScreen = '/spScreen';
static const cleanScreen = '/cleanScreen';
static const flutterScreen = '/flutterScreen';
static const offlineReadScreen = '/offline_readScreen';
static const offlinePreviewScreen = '/offline_previewScreen';
static const offlineScreen = '/offlineScreen';
static const otpScreen = '/otpScreen';
  static const topBooksScreen = '/topBooksScreen';
  static const categoryPreviewScreen = '/categoryPreviewScreen';
  static const previewScreen = '/previewScreen';
  static const subcriptionScreen = '/subcriptionScreen';
  static const freeTrialScreen = '/freeTrialScreen';
  static const supportScreen = '/supportScreen';
  static const paymentScreen = '/paymentScreen';
  static const updateProfileScreen = '/update_profileScreen';
  static const passChangeScreen = '/passChangeScreen';
  static const faqScreen = '/faqScreen';
  static const termsScreen = '/termsScreen';
  static const policyScreen = '/policyScreen';
  static const readingScreen = '/readingScreen';
  static const playerScreen = '/playerScreen';
  static const detailPreviewScreen = '/detailPreviewScreen';
  static const detailsScreen = '/detailsScreen';
  static const findScreen = '/findScreen';
  static const searchSongScreen = '/searchSongScreen';
  static const profileScreen = '/profileScreen';
  static const libraryScreen = '/libraryScreen';
  static const allCategoryScreen = '/all_categoryScreen';
  static const registerScreen = '/registerScreen';
  static const resetPasswordScreen = '/reset_passwordScreen';
  static const otpVerifyScreen = '/otp_verifyScreen';
  static const forgotPasswordScreen = '/forgot_passwordScreen';
  static const loginScreen = '/loginScreen';
  static const grambixScreen = '/grambixScreen';
  static const navigation = '/navigation';
  static const home = '/home';
  static const splashScreen = '/splashScreen';
}
